basePath: /api/v1
definitions:
  request.SubCreateRequest:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_title:
        type: string
      start_date:
        type: string
      user:
        type: string
    type: object
  request.SubUpdateRequest:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_title:
        type: string
      start_date:
        type: string
    type: object
  response.SubResponse:
    properties:
      end_date:
        type: string
      id:
        type: string
      price:
        type: integer
      service_title:
        type: string
      start_date:
        type: string
      user:
        type: string
    type: object
  response.SubSumResponse:
    properties:
      result:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample subscription management API
  title: Subscription API
  version: "1.0"
paths:
  /subscription/:
    get:
      consumes:
      - application/json
      description: Pageable subscription list
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.SubResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List subscription
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Create a new subscription
      parameters:
      - description: Subscription data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.SubCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.SubResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create new subscription
      tags:
      - subscriptions
  /subscription/{id}:
    delete:
      consumes:
      - application/json
      description: Delete subscription by ID
      parameters:
      - description: Subscription ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete subscription by ID
      tags:
      - subscriptions
    get:
      consumes:
      - application/json
      description: Get subscription by ID
      parameters:
      - description: Subscription ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SubResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get subscription by ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Update subscription by ID
      parameters:
      - description: Subscription ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: Subscription update request data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.SubUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SubResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update subscription by ID
      tags:
      - subscriptions
  /subscription/sum:
    get:
      consumes:
      - application/json
      description: Sum subscriptions price by specified period
      parameters:
      - description: Start period date
        format: date
        in: query
        name: start_period
        required: true
        type: string
      - description: End period date
        format: date
        in: query
        name: end_period
        required: true
        type: string
      - description: User ID filter
        format: uuid
        in: query
        name: userId
        type: string
      - description: Service title filter
        in: query
        name: service_title
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SubSumResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Sum subscriptions price
      tags:
      - subscriptions
swagger: "2.0"
